# Specify output directory
outdir: NA

# Specify resources directory. Set to NA to use default (resources)
resdir: NA

# Specify reference data directory. Set to NA to use default (1KG+HGDP)
refdir: NA

# Location of this config file
config_file: NA

# Specify location of gwas_list file
gwas_list: NA

# Specify location of target_list file
target_list: NA

# Specify location of score_list file
score_list: NA

# Specify pgs_methods ('ptclump','dbslmm','prscs','sbayesr','lassosum','ldpred2','megaprs')
pgs_methods: NA

# Specify p-value thresholds for ptclump
ptclump_pts: ['5e-8', '1e-6', '1e-4', '1e-2', '0.1', '0.2', '0.3', '0.4', '0.5', '1']

# Specify SNP-h2 folds in DBSLMM (1 = corresponds to default model)
dbslmm_h2f: ['0.8', '1', '1.2']

# Specify phi parameters for PRS-CS
prscs_phi: ['1e-6', '1e-4', '1e-2', '1', 'auto']

# Specify 1kg or ukb ld reference for PRS-CS
prscs_ldref: '1kg'

# Specify models for LDpred2
ldpred2_model: ['grid', 'auto', 'inf']

# Specify models for LDpred2-auto should be used for inference of h2, p, and alpha
ldpred2_inference: T

# Specify ancestry classification probability threshold
ancestry_prob_thresh: 0.95

# Specify if you want test mode. Set to NA if you don't want test mode
testing: NA
