# Specify output directory
outdir: NA

# Specify reference data directory. Set to NA to use default (1KG+HGDP)
refdir: NA

# Location of this config file
config_file: NA

# Specify location of gwas_list file
gwas_list: NA

# Specify location of target_list file
target_list: NA

# Specify location of score_list file
score_list: NA

# Specify pgs_methods ('ptclump','dbslmm','prscs','sbayesr','lassosum','ldpred2','megaprs')
pgs_methods: NA

# Specify if you want test mode. Set to NA if you don't want test mode
testing: NA
