gwas_list: /users/k1806347/brc_scratch/Software/MyGit/GenoPred/GenoPredPipe/resources/data/gwas/gwas_list.txt
target_list: /users/k1806347/brc_scratch/Software/MyGit/GenoPred/GenoPredPipe/resources/data/target/target_list_example.txt
