name: CI Test Pipeline

on:
  pull_request:
    branches:
      - master
    paths:
      - 'scripts/**'
      - 'functions/**'
      - 'pipeline/rules/**'
      - 'pipeline/tests/**'

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: mambaorg/micromamba:latest
      options: --entrypoint /bin/bash

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        
    - name: Set up Mamba environment
      run: |
        # Initialize micromamba
        source /usr/local/etc/profile.d/micromamba.sh

        # Create the genopred environment using mamba
        micromamba create --name genopred --file /pipeline/envs/pipeline.yaml

    - name: Install R v4.3.0
      run: |
        micromamba install -y -c conda-forge r-base=4.3.0

    - name: Run tests
      run: |
        source ~/.bashrc
        micromamba activate genopred
        R -e "install.packages('testthat', repos='http://cran.rstudio.com')"
        R -e "testthat::test_dir('pipeline/tests/testthat')"
