name: CI Test Pipeline

on:
  push:
    branches:
      - dev
    paths:
      - 'scripts/**'
      - 'functions/**'
      - 'pipeline/rules/**'
      - 'pipeline/tests/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: mambaorg/micromamba:latest
      options: --entrypoint /bin/bash --user root

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: opain/GenoPred
        token: ${{ secrets.GITHUB_TOKEN }}
        ssh-strict: true
        ssh-user: git
        persist-credentials: true
        clean: true
        sparse-checkout-cone-mode: true
        fetch-depth: 1
        fetch-tags: false
        show-progress: true
        lfs: false
        submodules: false
        set-safe-directory: true

    - name: Set up Mamba environment
      shell: bash
      run: |
        # Ensure we are in the correct working directory
        cd $GITHUB_WORKSPACE
        
        # Initialize micromamba
        micromamba shell init -s bash -p ~/micromamba
        eval "$(micromamba shell hook -s bash)"

        # Create the genopred environment using mamba
        micromamba create --name genopred --file /pipeline/envs/pipeline.yaml

    - name: Install R v4.3.0
      shell: bash
      run: |
        micromamba install -y -c conda-forge r-base=4.3.0

    - name: Run tests
      shell: bash
      run: |
        eval "$(micromamba shell hook -s bash)"
        micromamba activate genopred
        R -e "install.packages('testthat', repos='http://cran.rstudio.com')"
        R -e "testthat::test_dir('pipeline/tests/testthat')"
